using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using TMPro;

public partial class UIManager
{
    private GameObject CreateEndingTreeContent(Transform parent)
    {
        var go = GameObject.Find("EndingTreeContent");
        if (go != null)
            return go;
        go = new GameObject("EndingTreeContent");
        go.transform.SetParent(parent, false);

        var rect = go.AddComponent<RectTransform>();
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
        rect.pivot = new Vector2(0.5f, 0.5f);

        var img = go.AddComponent<Image>();
        img.color = new Color(0f, 0f, 0f, 0f);
        img.raycastTarget = true;

        var pan = go.AddComponent<EndingTreePanZoom>();
        pan.Init(rect);
        return go;
    }

    private class EndingTreePanZoom : MonoBehaviour, IPointerDownHandler, IDragHandler, IPointerUpHandler, IScrollHandler
    {
        private RectTransform _rect;
        private Vector2 _dragStartPos;
        private Vector2 _startAnchorPos;
        private bool _dragging;

        public void Init(RectTransform rect)
        {
            _rect = rect;
        }

        public void OnPointerDown(PointerEventData eventData)
        {
            _dragging = true;
            _dragStartPos = eventData.position;
            _startAnchorPos = _rect != null ? _rect.anchoredPosition : Vector2.zero;
        }

        public void OnDrag(PointerEventData eventData)
        {
            if (!_dragging || _rect == null)
                return;
            _rect.anchoredPosition = _startAnchorPos + (eventData.position - _dragStartPos);
        }

        public void OnPointerUp(PointerEventData eventData)
        {
            _dragging = false;
        }

        public void OnScroll(PointerEventData eventData)
        {
            if (_rect == null)
                return;
            float scroll = eventData.scrollDelta.y;
            if (Mathf.Approximately(scroll, 0f))
                return;
            float factor = scroll > 0f ? 1.15f : 1f / 1.15f;
            float ns = Mathf.Clamp(_rect.localScale.x * factor, UIManager.EndingTreeZoomMin, UIManager.EndingTreeZoomMax);
            _rect.localScale = Vector3.one * ns;
        }
    }

    private GameObject CreateTreeLine(string name, Transform parent, Vector2 start, Vector2 end, float thickness, Color color)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);

        var rect = go.AddComponent<RectTransform>();
        rect.anchorMin = new Vector2(0.5f, 0.5f);
        rect.anchorMax = new Vector2(0.5f, 0.5f);
        rect.pivot = new Vector2(0.5f, 0.5f);
        rect.anchoredPosition = (start + end) * 0.5f;
        Vector2 delta = end - start;
        rect.sizeDelta = new Vector2(Mathf.Max(delta.magnitude, thickness), thickness);
        rect.localRotation = Quaternion.Euler(0f, 0f, Mathf.Atan2(delta.y, delta.x) * Mathf.Rad2Deg);

        var img = go.AddComponent<Image>();
        img.color = color;
        go.transform.SetAsFirstSibling();
        return go;
    }

    private void BuildEndingTreeLayout()
    {
        _endingRowTexts = new TMP_Text[Endings.Length];
        _endingQuestUis.Clear();

        float sw = Screen.width;
        float sh = Screen.height;
        float k = 1.3f;
        var lineColor = new Color(1f, 1f, 1f, 0.55f);
        var doneLine = new Color(0.35f, 0.9f, 0.45f, 0.8f);
        var silenceLine = new Color(0.95f, 0.4f, 0.4f, 0.8f);
        var treeParent = _endingTreeContent != null ? _endingTreeContent.transform : _endingTreePanel.transform;

        // Clear any tree nodes generated by a previous build (InitializeUI can run more than
        // once), so boxes/lines no longer created by the current quest config don't linger.
        for (int i = treeParent.childCount - 1; i >= 0; i--)
            Object.DestroyImmediate(treeParent.GetChild(i).gameObject);

        // Ending nodes: one horizontal row (ordered to keep parent/child clusters close).
        Vector2[] nodePos = new Vector2[Endings.Length];
        var nodeSize = new Vector2(Mathf.Min(sw * 0.098f, 192f) * k, Mathf.Max(44f, sh * 0.055f) * k);
        int[] rowOrder = { 3, 7, 0, 1, 5, 2, 4, 6 };
        float eGap = Mathf.Min(sw * 0.012f, 18f) * k;
        float totalRowW = nodeSize.x * rowOrder.Length + eGap * (rowOrder.Length - 1);
        for (int r = 0; r < rowOrder.Length; r++)
            nodePos[rowOrder[r]] = new Vector2(-totalRowW * 0.5f + r * (nodeSize.x + eGap) + nodeSize.x * 0.5f, 0f);

        for (int i = 0; i < Endings.Length; i++)
        {
            int index = i;
            var btn = CreateButton("EndingRow" + i, treeParent, Localization.T(Endings[i].TitleKey),
                nodePos[i], () => ShowEndingDetail(true, index), nodeSize);
            var btnText = btn.GetComponentInChildren<TMP_Text>();
            if (btnText != null)
                btnText.fontSize = Mathf.Max(11, (int)(sh * 0.013f * k));
            _endingRowTexts[i] = btnText;
        }

        // Parent/child ending branches (dim connectors under the row)
        for (int i = 0; i < Endings.Length; i++)
        {
            int parent = -1;
            if (i == 0 || i == 1 || i == 4) parent = 3;
            else if (i == 5) parent = 0;
            else if (i == 2) parent = 1;
            else if (i == 6) parent = 4;
            else if (i == 7) parent = 3;
            if (parent < 0) continue;
            Vector2 from = new Vector2(nodePos[parent].x, -nodeSize.y * 0.5f - 22f * k);
            Vector2 to = new Vector2(nodePos[i].x, -nodeSize.y * 0.5f - 22f * k);
            CreateTreeLine("EndingBranch_" + parent + "_" + i, treeParent, from, to, 2.5f, lineColor);
        }

        // Aggregate unique quests across endings (one box per quest)
        var questUis = new List<EndingQuestUi>();
        for (int i = 0; i < Endings.Length && i < EndingQuestDefs.Length; i++)
        {
            var quests = EndingQuestDefs[i];
            if (quests == null) continue;
            for (int j = 0; j < quests.Length; j++)
            {
                var def = quests[j];
                EndingQuestUi ui = null;
                for (int u = 0; u < questUis.Count; u++)
                {
                    if (questUis[u].Def.QuestName == def.QuestName)
                    {
                        ui = questUis[u];
                        break;
                    }
                }
                if (ui == null)
                {
                    ui = new EndingQuestUi { Def = def };
                    questUis.Add(ui);
                }
                if (!ui.Targets.Exists(t => t.Key == i))
                    ui.Targets.Add(new KeyValuePair<int, bool>(i, def.MustComplete));
            }
        }

        // Sort quest boxes: mansion (fewest targets) left, mansion_secret (most) right
        questUis.Sort((a, b) =>
        {
            int aCount = a.Targets.Count;
            int bCount = b.Targets.Count;
            if (aCount != bCount) return aCount.CompareTo(bCount);
            return string.Compare(a.Def.QuestName, b.Def.QuestName, System.StringComparison.Ordinal);
        });

        // Quest row at the top (one box per quest)
        var questSize = new Vector2(Mathf.Min(sw * 0.115f, 195f) * k, Mathf.Max(34f, sh * 0.05f) * k);
        float qGap = Mathf.Min(sw * 0.02f, 28f) * k;
        float questY = sh * 0.34f * k;
        int qc = questUis.Count;
        float totalW = questSize.x * qc + qGap * (qc - 1);
        bool[] markerAdded = new bool[Endings.Length];
        for (int q = 0; q < qc; q++)
        {
            var ui = questUis[q];
            float qx = -totalW * 0.5f + q * (questSize.x + qGap) + questSize.x * 0.5f;

            var boxImg = CreateTreeBox("EndingQuestRect_" + q, treeParent, new Vector2(qx, questY), questSize, new Color(0.2f, 0.2f, 0.28f, 1f));
            ui.Box = boxImg;
            var qBtn = boxImg.gameObject.GetComponent<Button>();
            if (qBtn == null)
                qBtn = boxImg.gameObject.AddComponent<Button>();
            qBtn.targetGraphic = boxImg;
            qBtn.onClick.RemoveAllListeners();
            qBtn.onClick.AddListener(() => ShowEndingQuestTab(true, ui));
            var qLabel = EnsureText("EndingQuestLabel_" + q, new Vector2(qx, questY), Localization.T(ui.Def.QuestName),
                Mathf.Max(10, (int)(sh * 0.011f * k)), treeParent, TextAlignmentOptions.Center, true, new Vector2(questSize.x * 0.95f, questSize.y * 0.8f));
            qLabel.color = Color.white;
            ui.Text = qLabel;

            Vector2 qBottom = new Vector2(qx, questY - questSize.y * 0.5f);
            for (int t = 0; t < ui.Targets.Count; t++)
            {
                int ending = ui.Targets[t].Key;
                bool mustComplete = ui.Targets[t].Value;
                Vector2 eTop = new Vector2(nodePos[ending].x, nodePos[ending].y + nodeSize.y * 0.5f);
                CreateTreeLine("EndingQuestLine_" + q + "_" + ending, treeParent, qBottom, eTop, 3f,
                    mustComplete ? doneLine : silenceLine);
                if (ending >= 0 && ending < SpecialChoiceEndings.Length && SpecialChoiceEndings[ending] && !markerAdded[ending])
                {
                    markerAdded[ending] = true;
                    var mSize = new Vector2(Mathf.Max(96f, nodeSize.x * 0.56f), Mathf.Max(20f, sh * 0.024f * k));
                    Vector2 mPos = new Vector2(eTop.x, eTop.y + mSize.y * 0.5f + 4f);
                    CreateTreeBox("SpecialChoiceBox_" + ending, treeParent, mPos, mSize, new Color(0.85f, 0.7f, 0.2f, 0.95f));
                    var mLabel = EnsureText("SpecialChoiceLabel_" + ending, mPos, Localization.T("Lựa chọn đặc biệt"),
                        Mathf.Max(9, (int)(sh * 0.010f * k)), treeParent, TextAlignmentOptions.Center, true, new Vector2(mSize.x * 0.95f, mSize.y * 0.9f));
                    mLabel.color = new Color(0.05f, 0.05f, 0.05f, 1f);
                }
            }
            _endingQuestUis.Add(ui);
        }
    }

    private Image CreateTreeBox(string name, Transform parent, Vector2 position, Vector2 size, Color color)
    {
        var go = GameObject.Find(name);
        if (go != null)
            return go.GetComponent<Image>();
        go = new GameObject(name);
        go.transform.SetParent(parent, false);
        var rect = go.AddComponent<RectTransform>();
        rect.anchorMin = new Vector2(0.5f, 0.5f);
        rect.anchorMax = new Vector2(0.5f, 0.5f);
        rect.pivot = new Vector2(0.5f, 0.5f);
        rect.anchoredPosition = position;
        rect.sizeDelta = size;
        var img = go.AddComponent<Image>();
        img.color = color;
        return img;
    }

    private void RefreshEndingTree()
    {
        if (_endingQuestUis == null)
            return;
        for (int i = 0; i < _endingQuestUis.Count; i++)
        {
            var ui = _endingQuestUis[i];
            if (ui == null || ui.Def == null || ui.Text == null)
                continue;
            bool done = false;
            if (QuestManager.Instance != null)
            {
                done = QuestManager.Instance.IsNamedQuestComplete(ui.Def.QuestName) || QuestManager.Instance.IsComplete(ui.Def.Target);
            }
            ui.Text.text = Localization.T(ui.Def.QuestName);
            if (ui.Box != null)
                ui.Box.color = done ? new Color(0.15f, 0.4f, 0.2f, 1f) : new Color(0.45f, 0.15f, 0.15f, 1f);
        }
    }

    private void ShowEndingQuestTab(bool show, EndingQuestUi ui = null)
    {
        if (_endingQuestTabPanel == null)
            return;
        if (show && ui != null)
        {
            _endingQuestTabUi = ui;
            RefreshEndingQuestTab(ui);
        }
        _endingQuestTabPanel.SetActive(show);
        if (show && _settingsPanel != null)
            _settingsPanel.SetActive(false);
    }

    private void RefreshEndingQuestTab(EndingQuestUi ui)
    {
        if (ui == null || ui.Def == null || _endingQuestTabPanel == null)
            return;

        var title = _endingQuestTabPanel.transform.Find("EndingQuestTabBox/EndingQuestTabTitle");
        if (title != null)
        {
            var t = title.GetComponent<TMP_Text>();
            if (t != null)
                t.text = Localization.T(ui.Def.QuestName);
        }

        string story = null;
        if (QuestManager.Instance != null)
            story = QuestManager.Instance.GetQuestDescription(ui.Def.QuestName);
        if (string.IsNullOrEmpty(story))
            story = Localization.T("Quỷ Vương đã thức tỉnh ở cuối con đường phía đông. Dùng Tràng Hạt tiêu diệt nó để bảo vệ làng!");

        var storyObj = _endingQuestTabPanel.transform.Find("EndingQuestTabBox/EndingQuestTabStory");
        if (storyObj != null)
        {
            var s = storyObj.GetComponent<TMP_Text>();
            if (s != null)
                s.text = story;
        }

        string target = null;
        int count = 0;
        int requiredDay = 0;
        if (QuestManager.Instance != null)
            QuestManager.Instance.TryGetQuestInfo(ui.Def.QuestName, out target, out count, out requiredDay);

        string unlockText;
        if (ui.Def.QuestName == "Trấn Áp Quỷ Vương")
            unlockText = Localization.T("Hoàn thành 'Trừ Tà Quanh Chùa' và nói chuyện với thầy ở chùa");
        else if (ui.Def.QuestName == "Xây Dựng Dinh Thự Cho Jessica")
            unlockText = Localization.T("Tỏ tình với Jessica và cô ấy đồng ý");
        else if (requiredDay > 0)
            unlockText = Localization.F("Mở khóa ngày {0}", requiredDay);
        else
            unlockText = Localization.T("Tự động mở khóa");

        string objective = GetQuestObjectiveText(target, count);
        string objectiveLine = "";
        if (!string.IsNullOrEmpty(objective))
        {
            int progress = QuestManager.Instance != null ? QuestManager.Instance.GetNamedQuestProgress(ui.Def.QuestName) : 0;
            bool money = target == "money_earned";
            string progressText = money ? progress.ToString("N0") : progress.ToString();
            string countText = money ? count.ToString("N0") : count.ToString();
            objectiveLine = "• " + objective + " (" + progressText + "/" + countText + ")";
        }

        var sb = new StringBuilder();
        sb.AppendLine(Localization.T("Điều kiện mở khóa:"));
        sb.AppendLine("• " + unlockText);
        sb.AppendLine();
        sb.AppendLine(Localization.T("Điều kiện hoàn thành:"));
        if (!string.IsNullOrEmpty(objectiveLine))
            sb.AppendLine(objectiveLine);
        sb.AppendLine();
        sb.AppendLine(Localization.T("Kết thúc liên quan:"));
        for (int t = 0; t < ui.Targets.Count; t++)
        {
            int ending = ui.Targets[t].Key;
            bool mustComplete = ui.Targets[t].Value;
            if (ending < 0 || ending >= Endings.Length)
                continue;
            string req = mustComplete
                ? "<color=#59E673>" + Localization.T("Cần hoàn thành") + "</color>"
                : "<color=#F26666>" + Localization.T("Cần im lặng") + "</color>";
            sb.AppendLine("• " + Localization.T(Endings[ending].TitleKey) + " — " + req);
        }

        var condObj = _endingQuestTabPanel.transform.Find("EndingQuestTabBox/EndingQuestTabCond");
        if (condObj != null)
        {
            var c = condObj.GetComponent<TMP_Text>();
            if (c != null)
                c.text = sb.ToString();
        }
    }

    private string GetQuestObjectiveText(string target, int count)
    {
        switch (target)
        {
            case "boss_kill": return Localization.F("Tiêu diệt Quỷ Vương {0} lần", count);
            case "mansion_secret": return Localization.F("Lấy bằng chứng bí mật của Phú Ông {0} lần", count);
            case "money_earned": return Localization.F("Kiếm {0:N0} vàng", count);
            case "mansion": return Localization.F("Xây dựng {0} phần dinh thự", count);
            default: return string.IsNullOrEmpty(target) ? "" : target + " x" + count;
        }
    }

    public void ShowEndingTreePanel(bool show)
    {
        if (_endingTreePanel != null)
            _endingTreePanel.SetActive(show);
        if (!show)
        {
            if (_endingQuestTabPanel != null)
                _endingQuestTabPanel.SetActive(false);
            if (_endingDetailPanel != null)
                _endingDetailPanel.SetActive(false);
        }
        if (_settingsPanel != null && show)
            _settingsPanel.SetActive(false);
        if (show)
        {
            _pauseMenuPanel?.SetActive(false);
            _mainMenuPanel?.SetActive(false);
            ShowEndingList();
            RefreshEndingTree();
            GameInput.SetCursorLocked(false);
        }
        else
        {
            if (GameManager.Instance != null && GameManager.Instance.GamePaused)
                ShowPauseMenu(true);
            else if (GameManager.Instance != null && !GameManager.Instance.InGame)
                ShowMainMenu(true);
        }
    }

    public void ShowEndingList()
    {
        if (_endingTreeTitleText != null)
            _endingTreeTitleText.text = Localization.T("CÂY KẾT THÚC");
        if (_endingTreeSettingsButton != null)
            _endingTreeSettingsButton.gameObject.SetActive(true);
    }

    public void PlayEndingScene(int index)
    {
        if (index < 0 || index >= Endings.Length)
            return;
        if (!Endings[index].Unlocked)
            return;
        var cm = GameManager.Instance != null ? GameManager.Instance.CutsceneManager : null;
        if (cm == null)
            return;
        if (_endingTreePanel != null)
            _endingTreePanel.SetActive(false);
        switch (index)
        {
            case 0: cm.PlayDemonEnding(OnEndingSceneDone); break;
            case 1: cm.PlayJusticeEnding(OnEndingSceneDone); break;
            case 2: cm.PlayBlackmailEnding(OnEndingSceneDone); break;
            case 3: cm.PlayHappyEnding(OnEndingSceneDone); break;
            case 4: cm.PlayNtrEnding(OnEndingSceneDone); break;
            case 5: cm.PlayBossBadEnding(OnEndingSceneDone); break;
            case 6: cm.PlaySadEnding(OnEndingSceneDone); break;
            case 7: cm.PlayFatedEnding(OnEndingSceneDone); break;
        }
    }

    private void OnEndingSceneDone()
    {
        ShowEndingTreePanel(true);
    }

    public void ShowEndingDetail(bool show, int index = -1)
    {
        if (_endingDetailPanel == null)
            return;
        if (show && index >= 0 && index < Endings.Length)
        {
            _endingDetailIndex = index;
            RefreshEndingDetail(index);
        }
        _endingDetailPanel.SetActive(show);
        if (show && _settingsPanel != null)
            _settingsPanel.SetActive(false);
    }

    private void RefreshEndingDetail(int index)
    {
        if (index < 0 || index >= Endings.Length || _endingDetailPanel == null)
            return;

        var title = _endingDetailPanel.transform.Find("EndingDetailBox/EndingDetailTitle");
        if (title != null)
        {
            var t = title.GetComponent<TMP_Text>();
            if (t != null)
                t.text = Localization.T(Endings[index].TitleKey);
        }

        var story = _endingDetailPanel.transform.Find("EndingDetailBox/EndingDetailStory");
        if (story != null)
        {
            var s = story.GetComponent<TMP_Text>();
            if (s != null)
                s.text = Localization.T(Endings[index].ContentKey);
        }

        var sb = new StringBuilder();
        sb.AppendLine(Localization.T("Điều kiện hoàn thành:"));
        var quests = (index < EndingQuestDefs.Length) ? EndingQuestDefs[index] : null;
        if (quests != null && quests.Length > 0)
        {
            for (int j = 0; j < quests.Length; j++)
            {
                var def = quests[j];
                bool done = false;
                if (QuestManager.Instance != null)
                    done = QuestManager.Instance.IsNamedQuestComplete(def.QuestName) || QuestManager.Instance.IsComplete(def.Target);
                string status = done
                    ? "<color=#59E673>" + Localization.T("Đã hoàn thành") + "</color>"
                    : "<color=#F26666>" + Localization.T("Chưa hoàn thành") + "</color>";
                string req = def.MustComplete
                    ? Localization.T("Cần hoàn thành")
                    : Localization.T("Cần im lặng");
                sb.AppendLine("• " + Localization.T(def.QuestName) + " — " + status + " (" + req + ")");
            }
        }
        else
        {
            sb.AppendLine(Localization.T("Không có điều kiện"));
        }
        if (index >= 0 && index < SpecialChoiceEndings.Length && SpecialChoiceEndings[index] &&
            index < EndingChoiceTexts.Length && !string.IsNullOrEmpty(EndingChoiceTexts[index]))
        {
            sb.AppendLine();
            sb.AppendLine(Localization.T("Lựa chọn đặc biệt:"));
            sb.AppendLine("• <color=#E6C760>" + Localization.T(EndingChoiceTexts[index]) + "</color>");
        }
        if (!Endings[index].Unlocked)
        {
            sb.AppendLine();
            sb.AppendLine("<color=#F26666>" + Localization.T("Chưa mở khóa") + "</color>");
        }

        var condObj = _endingDetailPanel.transform.Find("EndingDetailBox/EndingDetailCond");
        if (condObj != null)
        {
            var c = condObj.GetComponent<TMP_Text>();
            if (c != null)
                c.text = sb.ToString();
        }
    }

    private void PlayEndingFromDetail()
    {
        if (_endingDetailIndex < 0)
            return;
        if (_endingDetailPanel != null)
            _endingDetailPanel.SetActive(false);
        PlayEndingScene(_endingDetailIndex);
    }
}
